// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVKRDOg8q_ZvndBEwjKnemdcLwa8Hl1i4',
    appId: '1:283447622164:web:6369f9ed614062d96c4501',
    messagingSenderId: '283447622164',
    projectId: 'app-web2-12a80',
    authDomain: 'app-web2-12a80.firebaseapp.com',
    databaseURL: 'https://app-web2-12a80-default-rtdb.firebaseio.com',
    storageBucket: 'app-web2-12a80.firebasestorage.app',
    measurementId: 'G-KFCZ15B7WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLHLxLjd12UFDFVMOD2VKPzgo60m_eNsA',
    appId: '1:283447622164:android:13b40078ca4fe5c76c4501',
    messagingSenderId: '283447622164',
    projectId: 'app-web2-12a80',
    databaseURL: 'https://app-web2-12a80-default-rtdb.firebaseio.com',
    storageBucket: 'app-web2-12a80.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVKRDOg8q_ZvndBEwjKnemdcLwa8Hl1i4',
    appId: '1:283447622164:web:1e6bbe18d753806d6c4501',
    messagingSenderId: '283447622164',
    projectId: 'app-web2-12a80',
    authDomain: 'app-web2-12a80.firebaseapp.com',
    databaseURL: 'https://app-web2-12a80-default-rtdb.firebaseio.com',
    storageBucket: 'app-web2-12a80.firebasestorage.app',
    measurementId: 'G-JX88YMLYFG',
  );
}
